GO
-- AdicionarMateria
CREATE OR ALTER PROCEDURE AdicionarMateria
(
    @SIGLA CHAR(3),
    @NOME VARCHAR(50),
    @CARGAHORARIA INT,
    @CURSO CHAR(3),
    @PROFESSOR INT
)
AS BEGIN
    INSERT INTO MATERIAS (
        SIGLA, NOME, CARGAHORARIA, CURSO, PROFESSOR
    )
    VALUES (
        @SIGLA, @NOME, @CARGAHORARIA, @CURSO, @PROFESSOR
    )
END

EXEC AdicionarMateria @SIGLA = 'POO', @NOME = 'PROGRAMAÇÃO ORIENTADA A OBJETO', @CARGAHORARIA = 144, @CURSO = 'ENG', @PROFESSOR = 3
