GO
CREATE OR ALTER PROCEDURE AdicionarProfessor
(
    @NOME VARCHAR(50)
)
AS BEGIN
    INSERT INTO PROFESSOR(NOME)
    VALUES (@NOME)
    SELECT SCOPE_IDENTITY() AS PROFESSOR
END

EXEC AdicionarProfessor @NOME = 'Leanderson'