GO
-- REGISTRAR ALUNO PARA CURSO
CREATE OR ALTER PROCEDURE RegistrarMatricula
    @MATRICULA INT,
    @CURSO CHAR(3),
    @PERLETIVO INT
AS
BEGIN
    INSERT INTO MATRICULA (
        MATRICULA, CURSO, MATERIA, PROFESSOR, PERLETIVO
    )
    SELECT 
        @MATRICULA, 
        @CURSO, 
        SIGLA, 
        PROFESSOR, 
        @PERLETIVO
    FROM MATERIAS
    WHERE CURSO = @CURSO;
END;

